packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  vitest: '^3.2.4'
  '@biomejs/biome': '2.4.11'
  '@hookform/resolvers': '^5.2.2'
  '@types/react': '^19.2.14'
  '@types/react-dom': '^19.2.3'
  react: '^19.2.5'
  react-dom: '^19.2.5'
  typescript: '5.9.2'
  tsup: '^8.5.1'
  zod: '^4.3.6'
