import {
	AlertCircle,
	CalendarIcon,
	ChartArea,
	ChartColumn,
	Check,
	ChevronLeft,
	ChevronRight,
	Cog,
	DoorOpen,
	LayoutDashboard,
	LoaderCircle,
	Lock,
	LogOut,
	Mail,
	Pencil,
	PlusCircle,
	Scale,
	Trash,
	TrendingDown,
	TrendingUp,
	User,
	UserPlus,
	Users,
	X,
} from "lucide-react";

export const icons = {
	logout: LogOut,
	loader: LoaderCircle,
	dashboard: LayoutDashboard,
	income: TrendingUp,
	expense: TrendingDown,
	edit: Pencil,
	delete: Trash,
	add: PlusCircle,
	arrowLeft: ChevronLeft,
	arrowRight: ChevronRight,
	calendar: CalendarIcon,
	chartBar: ChartColumn,
	chartArea: ChartArea,
	user: User,
	group: Users,
	leave: DoorOpen,
	addUser: UserPlus,
	reject: X,
	accept: Check,
	error: AlertCircle,
	balance: Scale,
	email: Mail,
	password: Lock,
	settings: Cog,
};

export type IconName = keyof typeof icons;
