name: Format & Lint
description: Format and lint code

runs:
  using: "composite"
  steps:
    - name: Format code
      run: pnpm run format
      shell: bash

    - name: Lint code
      run: pnpm run lint
      shell: bash
